services:

  idsvr-admin:
    image: custom_idsvr:1.0.0
    hostname: idsvr-admin
    volumes:
      - ./license.json:/opt/idsvr/etc/init/license/license.json
      - ./config/cluster.xml:/opt/idsvr/etc/init/cluster.xml
    env_file:
      - ./config/parameters.env
      - ./vault/protected-secrets.env
    environment:
      ADMIN: 'true'
      SERVICE_NAME: 'Admin'
      LOGGING_LEVEL: 'DEBUG'

  idsvr-runtime1:
    image: custom_idsvr:1.0.0
    hostname: idsvr-runtime1
    volumes:
      - ./license.json:/opt/idsvr/etc/init/license/license.json
      - ./config/cluster.xml:/opt/idsvr/etc/init/cluster.xml
    env_file:
      - ./config/parameters.env
      - ./vault/protected-secrets.env
    environment:
      SERVICE_NAME: 'Runtime1'
      LOGGING_LEVEL: 'DEBUG'

  idsvr-runtime2:
    image: custom_idsvr:1.0.0
    hostname: idsvr-runtime2
    volumes:
      - ./license.json:/opt/idsvr/etc/init/license/license.json
      - ./config/cluster.xml:/opt/idsvr/etc/init/cluster.xml
    env_file:
      - ./config/parameters.env
      - ./vault/protected-secrets.env
    environment:
      SERVICE_NAME: 'Runtime2'
      LOGGING_LEVEL: 'DEBUG'

  curity-data:
    image: curity_mssql:1.0.0
    hostname: dbserver
    volumes:
    - ./data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password1
      MSSQL_COLLATION: Latin1_General_100_CI_AS_SC_UTF8
      MSSQL_AGENT_ENABLED: true

  api-gateway:
    image: kong/kong:latest
    hostname: apigateway
    ports:
      - 443:3000
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
      - ../../utils/ssl-certs/example.ssl.key:/usr/local/share/certs/example.ssl.key
      - ../../utils/ssl-certs/example.ssl.crt:/usr/local/share/certs/example.ssl.crt
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:3000 ssl'
      KONG_LOG_LEVEL: 'info'
      KONG_SSL_CERT: '/usr/local/share/certs/example.ssl.crt'
      KONG_SSL_CERT_KEY: './usr/local/share/certs/example.ssl.key'