services:
  curity-idsvr:
    image: curity.azurecr.io/curity/idsvr:latest
    hostname: idsvr
    ports:
      - 6749:6749
      - 80:8443
    volumes:
      - ./curity-config.xml:/opt/idsvr/etc/init/curity-config.xml
    environment:
      ADMIN: 'true'
      CONFIG_ENCRYPTION_KEY: '${CONFIG_ENCRYPTION_KEY}'
      LICENSE_KEY: '${LICENSE_KEY}'
      RUNTIME_BASE_URL: '${RUNTIME_BASE_URL}'
      ADMIN_BASE_URL: '${ADMIN_BASE_URL}'
